name: list-new-checks

on: 
  push:
    branches:
    - list-new-checks
    - master
jobs:
  list-new-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v2
      - name: Checkout previous commit 1/2
        uses: actions/checkout@v2
        with:
          path: previous
      - name: Checkout previous commit 2/2
        run: |
          git --git-dir ./previous/.git fetch
          git --git-dir ./previous/.git checkout master
          git --git-dir ./previous/.git checkout HEAD~1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python3 -m pip install pipenv
          pipenv install --dev
      - name: List and Diff Checks
        run: |
          PYTHONPATH=${PWD} pipenv run python ./checkov/main.py -l > latest-checks.txt
          PYTHONPATH=${PWD} pipenv run python ./previous/checkov/main.py -l > previous-checks.txt
          DIFF=$(diff previous-checks.txt latest-checks.txt)
          if [[ $DIFF != "" ]]; then echo "Diff exists, new check! \n "; echo ${DIFF}; else echo "No new checks this commit. Skipping Slack update" ; fi
      - name: Send slack message to CodifiedSecurity
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
          custom_payload: |
            {
              username: 'checkov-checkbot',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} succeeded in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          #GITHUB_TOKEN: ${{ github.token }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.