name: list-new-checks

on: 
  push:
    branches:
    - list-new-checks
    - master
jobs:
  list-new-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v2
      - name: Checkout previous commit 1/2
        uses: actions/checkout@v2
        with:
          path: previous
      - name: Checkout previous commit 2/2
        run: |
          git --git-dir ./previous/.git fetch
          git --git-dir ./previous/.git checkout master
          git --git-dir ./previous/.git checkout HEAD~1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python3 -m pip install pipenv
          pipenv install --dev
      - name: List and Diff Checks
        run: |
          PYTHONPATH=${PWD} pipenv run python ./checkov/main.py -l > latest-checks.txt 
          awk -F"|" '{ print $3 "|"  $4 "|" $5 "|" $6 "|" $7 }' latest-checks.txt > latest-filtered.txt
          PYTHONPATH=${PWD}/previous pipenv run python ./previous/checkov/main.py -l > previous-checks.txt
          awk -F"|" '{ print $3 "|"  $4 "|" $5 "|" $6 "|" $7 }' previous-checks.txt > previous-filtered.txt
          export DIFF=$(diff previous-filtered.txt latest-filtered.txt)
          echo ::set-env name=CHECKDIFF::${DIFF}
          echo ${CHECKDIFF}
          if [[ $DIFF != "" ]]; then echo "Diff exists, new check!"; echo ${DIFF}; else echo "No new checks this commit. Skipping Slack update" ; fi 
      - name: Send slack message to CodifiedSecurity
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
          custom_payload: |
            {
              username: 'checkov-checkbot',
              icon_emoji: ':octocat:',
              attachments: [{
                color: 'good',
                text: `Whoo! Checkov has a new check! \n Thanks ${process.env.AS_AUTHOR}!! \n Check ID: Test \n Check Details: Test2 \n in commit: ${process.env.AS_COMMIT} at ${process.env.AS_REPO} \n ${CHECKDIFF}`,
              }]
            }
        env:
          GITHUB_TOKEN: ${{ github.token }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: env.CHECKDIFF