name: list-new-checks

on: 
  push:
    branches:
    - master
jobs:
  list-new-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v2
      - name: Checkout previous commit 1/2
        uses: actions/checkout@v2
        with:
          path: previous
      - name: Checkout previous commit 2/2
        run: git --git-dir ./previous/.git checkout HEAD~1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: List and Diff Checks
        run: |
          PYTHONPATH=${PWD} pipenv run python ./checkov/main.py -l > latest-checks.txt
          PYTHONPATH=${PWD} pipenv run python ./previous/checkov/main.py -l > previous-checks.txt
          DIFF=$(diff previous-checks.txt latest-checks.txt)
          if [ $DIFF != "" ]; then echo "Diff exists, new check! \n "; echo ${DIFF}; fi
          